piyavkin.anton/T0/main.cpp

piyavkin.anton/T0

---

arakelyan.daniil/T0/main.cpp

arakelyan.daniil/T0

---

strelyaev.roman/T0/main.cpp

strelyaev.roman/T0

---

rebdev.pavel/T0/main.cpp

rebdev.pavel/T0

---

namestnikov.kirill/T0/main.cpp

namestnikov.kirill/T0

---

nikitov.dmitriy/T0/main.cpp

nikitov.dmitriy/T0

---

marishin.leonid/T0/main.cpp

marishin.leonid/T0

---

kravchenko.nikita/T0/main.cpp

------
1. Added neccesary folders
2. Added main.cpp

kravchenko.nikita/T0

---

demidenko.nikita/T0/main.cpp

demidenko.nikita/T0

---

zagrivnyy.aleksandr/T0/main.cpp

1. Added base directories structure
2. Added output of my fullname
--
Маленькую Лизу, глухую на одно ухо, мама ласково называла Моно Лиза.

zagrivnyy.aleksandr/T0

---

sakovskaia.maiia/T0/main.cpp

сын, увидев голубей, спрашивает маму "мам, у нас есть хлеб?" мама ему отвечает "без хлеба ешь"

sakovskaia.maiia/T0

---

feofanova.varvara/T0/main.cpp

feofanova.varvara/T0

---

babinov.serafim/main.cpp

babinov.serafim/T0

---

altun.efe/T0/main.cpp

В семье евреев-программистов не принято разговаривать о локалхосте.

altun.efe/T0

---

kozlov.nikita/T0/main.cpp

kozlov.nikita/T0

---

basko.ilya/T0/main.cpp

basko.ilya/T0

---

stepanchenko.sofya/T0/main.cpp

stepanchenko.sofya/T0

---

lebedev.anton/T0/main.cpp

lebedev.anton/T0

---

zolotukhin.andrey/T0/main.cpp

Наелся мужик сахара с дрожжами, теперь ходит бродит...

zolotukhin.andrey/T0

---

allaberdiev.ilnar/T0/main.cpp

— Как отыскать негра в темноте?
— Надо его рассмешить.

Allaberdiev.ilnar/T0

---

chistyakov.vladislav/T0/main.cpp

Chistyakov.vladislav/T0

---

lazareva.alisa/T0/main.cpp

lazareva.alisa/T0

---

arakelyan.daniil/T2/dataStruct.cpp
arakelyan.daniil/T2/dataStruct.hpp
arakelyan.daniil/T2/delimiter.cpp
arakelyan.daniil/T2/delimiter.hpp
arakelyan.daniil/T2/formatGuard.cpp
arakelyan.daniil/T2/formatGuard.hpp
arakelyan.daniil/T2/inFormatters.hpp
arakelyan.daniil/T2/inFormetters.cpp
arakelyan.daniil/T2/main.cpp

arakelyan.daniil/T2

---

skuratov.danil/T2/dataStruct.cpp
skuratov.danil/T2/dataStruct.hpp
skuratov.danil/T2/delimiter.cpp
skuratov.danil/T2/delimiter.hpp
skuratov.danil/T2/main.cpp
skuratov.danil/T2/nameOfKeys.cpp
skuratov.danil/T2/nameOfKeys.hpp
skuratov.danil/T2/numOfKey.cpp

skuratov.danil/T2

---

kuzmina.daria/T2/DataStruct.cpp
kuzmina.daria/T2/DataStruct.hpp
kuzmina.daria/T2/DelimiterI.cpp
kuzmina.daria/T2/DelimiterI.hpp
kuzmina.daria/T2/KeyI.cpp
kuzmina.daria/T2/KeyI.hpp
kuzmina.daria/T2/main.cpp

kuzmina.daria/T2

---

basko.ilya/T2/dataStruct.cpp
basko.ilya/T2/dataStruct.hpp
basko.ilya/T2/delimiters.cpp
basko.ilya/T2/delimiters.hpp
basko.ilya/T2/inputKey.cpp
basko.ilya/T2/inputKey.hpp
basko.ilya/T2/main.cpp
basko.ilya/T2/scopeGuard.cpp
basko.ilya/T2/scopeGuard.hpp

basko.ilya/T2

---

vorobieva.alyona/T0/main.cpp

vorobieva.alyona/T0

---

kazennov.ilia/T3/commands.cpp
kazennov.ilia/T3/commands.h
kazennov.ilia/T3/main.cpp
kazennov.ilia/T3/shapes.cpp
kazennov.ilia/T3/shapes.h

PERMS && INTERSECTIONS && INFRAME

kazennov.ilia/T3
